set(DISPLAYCLUSTER_PACKAGE_VERSION 0.2.0)
set(DISPLAYCLUSTER_REPO_URL https://github.com/smadhueagle/DisplayCluster.git)

set(DISPLAYCLUSTER_DEPENDS REQUIRED LibJpegTurbo Qt4)
set(DISPLAYCLUSTER_QT4_COMPONENTS "QtNetwork QtGui QtCore")
set(DISPLAYCLUSTER_CMAKE_ARGS -DBUILD_DISPLAYCLUSTER_LIBRARY=OFF -DBUILD_DESKTOPSTREAMER=ON -DENABLE_TUIO_TOUCH_LISTENER=OFF -DENABLE_PDF_SUPPORT=OFF -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release)

