set(EQOGRE_PACKAGE_VERSION 1.0.0)
set(EQOGRE_REPO_URL https://github.com/eile/eqOgre)
set(EQOGRE_DEPENDS REQUIRED Equalizer GLUT OGRE)
set(EQOGRE_DEB_DEPENDS pkg-config freeglut3-dev libogre-dev)
set(EQOGRE_FORCE_BUILD ${CI_BUILD})
